config/routes.rb
Michael::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'main#index'

  get 'contact/show', as: :contact

  resources :musicians, :only => [:show] do
    resources :gigs, :only => [:index]
    resources :pieces, :only => [:index]
    resources :musician_endorsements, :only => [:index]
    resources :musician_video_links, :only => [:index]
    resources :musician_images, :only => [:index]
    resources :genres, :only => [:index]
    resources :composers, :only => [:index]
    resources :musician_jobs, :only => [:index]
  end
  resources :genres, :only => [:show]
  resources :musician_jobs, :only => [:show]
  resources :composers, :only => [:show]
  resources :pieces, :only => [:show]
  resources :mentors, :only => [:show]
  resources :gigs, :only => [:show]
  resources :musician_endorsements, :only => [:show]
  resources :musician_video_links, :only => [:show]
  resources :musician_recording_files, :only => [:show]
  resources :accompanists, :only => [:show]
  resources :pianists, :only => [:show]
  resources :teachers, :only => [:show]
  resources :inquiries, :only => [:new, :create]
  resources :endorsements, :only => [:new, :create]

end

app/models/teacher.rb
class Teacher < Musician
end

app/controllers/teachers_controller.rb
class TeachersController < MusiciansController
  def show
    @musician = Teacher.singleton
    super
    @gigs = @gigs.take(1)
    @locations = @musician.teaching_locations.collect {|e| e.description}
  end
end

app/views/teachers/show.html.erb
<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script src="http://cdn.embed.ly/jquery.embedly-3.1.1.min.js"></script>
<script type="text/javascript">
  $('document').ready(function(){
    $('#video_url').embedly({
      query: { maxwidth: 300, wmode: 'transparent' },
      method: 'after',
      key: '454314ac5d2c4cfa990b5444d71874ef'
    });
  });
</script>
<%= form_for @musician do |f| %>
  <div class="row">
    <div class="span6">
      <div class="float-left">
        <%= link_to (image_tag @image_url, class: "img-circle"), musician_musician_images_path(@musician) %><br/>
        <small><div class="text-center"><%= link_to "Photo Gallery", musician_musician_images_path(@musician) %></div></small>
      </div>
      <p><%= @musician.my_story %></p>
      <p>
        <span class="bold">Education: </span>
        <%= @musician.education_summary %>
      </p>
      <p>
        <%= link_to "Inquire about lessons", new_inquiry_path %>
        <b>|</b>&nbsp
        <%= link_to "Endorse me!", new_endorsement_path %>
        <% @musician.musician_links.each do |e| %>
          <b>|</b>&nbsp
          <%= link_to e.link_for_display, e.url, target: "_blank" %>
        <% end %>
        <div class="row">
          <% if @video_link %>
            <div class="span4">
              <h3><%= link_to "Samples...", musician_musician_video_links_path(@musician) %></h3>
              <div id="video_url">
                <b><%= link_to @video_link.title, @video_link %></b></br>
                <%= link_to @video_link.url, @video_link.url %>
              </div>
            </div>
          <% end %>
        </div>
      <p>
    </div>
    <div class="span6">
      <b><%= link_to "Upcoming Recitals...", musician_gigs_path(@musician) %></b>
      <div class="boxed">
        <div class="table-responsive">
          <table class="table table-striped b-t text-sm">
            <tbody>
              <% @gigs.each do |e| %>
                <tr>
                  <td><div><%= if e.gig_image then (link_to (image_tag e.gig_image.image_url(:tiny).to_s), e) end %></div></td>
                  <td><%= link_to e.display_title, e %></td>
                  <td class="no_wrap_cell"><%= e.performance_date.strftime("%m-%d") %></td>
                  <td><%= e.timeframe %></td>
                  <td><%= e.location %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <p>
        <div class="text-boxed-3">
          <h4 class="center">Locations served:</h4>
          <div>
            <%= @locations.join(", ") %>
          </div>
        </div>
      </p>
      <% if @musician.musician_endorsements.present? %>
        <p>
          <h3><%= link_to "Testimonials...", musician_musician_endorsements_path(@musician) %></h3>
          <div class="table-responsive">
            <table class="table table-striped b-t text-sm">
              <tbody>
                <% @endorsements.each do |e| %>
                  <tr>
                    <td><%= link_to e.endorser_name, e %></td>
                    <td><%= e.abbreviated_description %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </p>
      <% end %>
      <% if !@jobs.empty? %>
        <div class="row">
          <div class="span4">
            <h3><%= link_to "Jobs...", musician_musician_jobs_path(@musician) %></h3>
            <div class="table-responsive">
              <table class="table table-striped b-t text-sm">
                <tbody>
                  <% @jobs.take(3).each do |e| %>
                    <tr>
                      <td><%= link_to e.title, e %></td>
                      <td><%= e.company %></td>
                      <td><%= e.short_description %></td>
                      <td><%= e.location %></td>
                      <td><%= e.duration %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <% if !@mentors.empty? %>
            <div class="span2">
              <h3>Mentors</h3>
              <div class="table-responsive">
                <table class="table table-striped b-t text-sm">
                  <tbody>
                    <% @mentors.each do |e| %>
                      <tr>
                        <td><%= if e.mentor_image then (link_to (image_tag e.mentor_image.image_url(:tiny).to_s), e) end %></td>
                        <td><%= link_to e.name, e %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>