config/routes.rb
Michael::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'main#index'

  get 'contact/show', as: :contact

  resources :musicians, :only => [:show] do
    resources :gigs, :only => [:index]
    resources :pieces, :only => [:index]
    resources :musician_endorsements, :only => [:index]
    resources :musician_video_links, :only => [:index]
    resources :musician_images, :only => [:index]
    resources :genres, :only => [:index]
    resources :composers, :only => [:index]
    resources :musician_jobs, :only => [:index]
  end
  resources :genres, :only => [:show]
  resources :musician_jobs, :only => [:show]
  resources :composers, :only => [:show]
  resources :pieces, :only => [:show]
  resources :mentors, :only => [:show]
  resources :gigs, :only => [:show]
  resources :musician_endorsements, :only => [:show]
  resources :musician_video_links, :only => [:show]
  resources :musician_recording_files, :only => [:show]
  resources :accompanists, :only => [:show]
  resources :pianists, :only => [:show]
  resources :teachers, :only => [:show]
  resources :inquiries, :only => [:new, :create]
  resources :endorsements, :only => [:new, :create]

end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(params[:inquiry])
    @inquiry.subject_type = "Endorsement"
    if @inquiry.deliver
      flash[:notice] = "Thank you! Your endorsement has been sent and I will post it as soon as possible."
      render :thank_you2
    else
      render :new
    end
  end
end

app/views/endorsements/_form.html.erb
<%= form_for @inquiry, url: endorsements_path, :html => {:class => 'form-inline', :method => :post} do |f| %>
  <p>
    <%= f.label :name, "Your name" %></br>
    <%= f.text_field :name %>
  </p><br/>
  <p>
    <%= f.label :email, "Your email address" %><br/>
    <%= f.text_field :email %>
  </p><br/>
  <p>
    <%= f.label :message, "Your endorsement" %><br/>
    <%= f.text_area :message, id: "message_area" %><br/><br/>
    <%= f.submit "Send", class: "btn btn-info"%>
  </p>
<% end %>

app/views/endorsements/new.html.erb
<h1>Send Endorsement to Michael</h2>
<%= render "form" %>

app/views/endorsements/thank_you2.html.erb
<h1>Thank you!</h1>
<p>Your endorsement has been sent and I will post it as soon as possible.</p>
<%= link_to "Home", root_path %>